#:schema node_modules/wrangler/config-schema.json
name = "adex-manager"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "AD_EXCLUSION_KV"
# ID se više ne definira ovdje radi sigurnosti (prebačeno u Cloudflare Dashboard).
# Potrebno ga je ručno povezati u sučelju: Settings > Functions > KV namespace bindings
